In [12]:
import pandas as pd
import numpy as np

In [33]:
data = pd.read_csv('consumer_psych_recommendation.csv')

/home/mikeal/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [34]:
data.head()

,consumer_id,consumer_dob,mhtp,consumer_gender,why_looking,prev_psych_experiences,diagnosis,proxy_id,proxy_first_name,proxy_last_name,...,self_matched,staff_matched,self_unmatched,staff_unmatched,psych_unmatched,viewed,sent_message,booked_appt,sessions,rating_avg
0,90851028,1982-01-01,True,M,shyness self esteem,NaN,NaN,1.0,NaN,NaN,...,False,False,NaN,NaN,NaN,False,NaN,False,NaN,NaN
1,90851028,1982-01-01,True,M,shyness self esteem,NaN,NaN,1.0,NaN,NaN,...,False,False,NaN,NaN,NaN,False,NaN,False,NaN,NaN
2,95763509,1980-01-01,True,F,Im feeling lost and stuck and confused about m...,NaN,NaN,1.0,NaN,NaN,...,False,False,NaN,NaN,NaN,False,NaN,False,NaN,NaN
3,90851028,1982-01-01,True,M,shyness self esteem,NaN,NaN,1.0,NaN,NaN,...,False,False,NaN,NaN,NaN,False,NaN,False,NaN,NaN
4,95763509,1980-01-01,True,F,Im feeling lost and stuck and confused about m...,NaN,NaN,1.0,NaN,NaN,...,False,False,NaN,NaN,NaN,False,NaN,False,NaN,NaN

In [35]:
def n_nan(df,column):
    
    # Count nans and find percentage
    
    percentage = df[column].value_counts().sum()/len(df)
    
    print(column, " = ",np.round(percentage*100,1))

In [36]:
data_columns = data.columns

In [54]:
for names in data_columns:
    
    n_nan(data, names)

consumer_id  =  100.0
consumer_dob  =  73.4
mhtp  =  100.0
consumer_gender  =  98.0
why_looking  =  86.2
prev_psych_experiences  =  2.9
diagnosis  =  3.6
proxy_id  =  97.9
proxy_first_name  =  1.8
proxy_last_name  =  0.6
psych_id  =  100.0
description  =  95.1
psych_gender  =  94.5
fees  =  84.1
headline  =  61.6
callout1  =  58.7
callout2  =  57.7
callout3  =  55.8
sliding_scale  =  78.3
is_visible  =  100.0
bulk_billing  =  80.1
rebate  =  83.9
likes_to_do  =  49.1
psych_dob  =  35.2
first_session  =  17.8
ndis  =  16.2
online_sessions  =  28.1
practising_since  =  29.5
therapeutic_approach  =  21.4
avg_rating  =  39.8
rating_valid_for_display  =  39.8
recommendation_id  =  100.0
preview_display_count  =  100.0
preview_rank_avg  =  100.0
self_shortlisted  =  100.0
staff_shortlisted  =  100.0
self_matched  =  100.0
staff_matched  =  100.0
self_unmatched  =  1.7
staff_unmatched  =  1.7
psych_unmatched  =  1.7
viewed  =  100.0
sent_message  =  6.7
booked_appt  =  100.0
sessions  =  6.7
rating_avg  =  0.1

In [70]:
# Drop all last values

drop_columns = ['rating_avg', 
                'sessions',
                'booked_appt', 
                'sent_message', 
                'viewed', 
                'psych_unmatched',
                'staff_unmatched',
                'self_unmatched',
                'staff_matched',
                'self_matched',
                'staff_shortlisted',
                'recommendation_id',
                'proxy_first_name',
                'proxy_last_name',
                'diagnosis',
                'first_session',
                'ndis',
                'why_looking',
                'description',
                'headline',
                'likes_to_do',
                'therapeutic_approach',
                'callout1',
                'callout2',
                'callout3',
                
                
               ]

In [71]:
data.drop(drop_columns,1)

,consumer_id,consumer_dob,mhtp,consumer_gender,prev_psych_experiences,proxy_id,psych_id,psych_gender,fees,sliding_scale,...,bulk_billing,rebate,psych_dob,online_sessions,practising_since,avg_rating,rating_valid_for_display,preview_display_count,preview_rank_avg,self_shortlisted
0,90851028,1982-01-01,True,M,NaN,1.0,8831884,M,160.0,False,...,False,84.8,NaN,NaN,NaN,NaN,NaN,17,23.647059,False
1,90851028,1982-01-01,True,M,NaN,1.0,8653175,F,199.0,False,...,False,84.8,NaN,NaN,NaN,NaN,NaN,14,35.000000,False
2,95763509,1980-01-01,True,F,NaN,1.0,8653175,F,199.0,False,...,False,84.8,NaN,NaN,NaN,NaN,NaN,3,35.333333,False
3,90851028,1982-01-01,True,M,NaN,1.0,8447728,M,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17,18.176471,False
4,95763509,1980-01-01,True,F,NaN,1.0,8453466,F,195.0,True,...,True,124.5,1968-01-01,NaN,1997-01-01,4.0,False,3,26.333333,False
5,95763509,1980-01-01,True,F,NaN,1.0,8443112,F,140.0,True,...,False,84.8,NaN,True,NaN,5.0,False,4,21.250000,False
6,90851028,1982-01-01,True,M,NaN,1.0,8402310,NaN,165.0,False,...,False,84.8,NaN,NaN,NaN,NaN,NaN,14,29.000000,False
7,90851028,1982-01-01,True,M,NaN,1.0,8510281,F,124.8,True,...,False,84.8,1989-01-01,NaN,2016-01-01,NaN,NaN,14,34.000000,False
8,90851028,1982-01-01,True,M,NaN,1.0,8274369,F,140.0,True,...,True,84.8,1980-01-01,NaN,2008-01-01,5.0,False,17,5.352941,False
9,93556988,1999-01-01,False,F,NaN,1.0,8274369,F,140.0,True,...,True,84.8,1980-01-01,NaN,2008-01-01,5.0,False,5,3.800000,False
10,91302178,1987-01-01,False,M,NaN,1.0,8274369,F,140.0,True,...,True,84.8,1980-01-01,NaN,2008-01-01,5.0,False,1,8.000000,False
11,93177299,1997-01-01,False,F,1st one-I did not feel like i was taken seriou...,NaN,8551750,F,190.0,True,...,False,124.5,1975-01-01,True,NaN,4.8,True,6,4.166667,False
12,90851028,1982-01-01,True,M,NaN,1.0,8485574,M,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,37.000000,False
13,95763509,1980-01-01,True,F,NaN,1.0,8588814,F,140.0,True,...,True,84.8,1975-01-01,NaN,NaN,NaN,NaN,4,9.500000,False
14,90851028,1982-01-01,True,M,NaN,1.0,8491708,F,160.0,False,...,False,84.8,1973-01-01,NaN,2004-01-01,NaN,NaN,15,26.800000,False
15,95763509,1980-01-01,True,F,NaN,1.0,8491708,F,160.0,False,...,False,84.8,1973-01-01,NaN,2004-01-01,NaN,NaN,3,30.333333,False
16,90851028,1982-01-01,True,M,NaN,1.0,8988493,F,155.0,False,...,False,84.8,NaN,True,NaN,5.0,False,17,4.352941,False
17,90851028,1982-01-01,True,M,NaN,1.0,8461744,M,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,43.000000,False
18,90851028,1982-01-01,True,M,NaN,1.0,8362681,F,200.0,False,...,False,124.5,1988-01-01,NaN,NaN,NaN,NaN,14,21.000000,False
19,95763509,1980-01-01,True,F,NaN,1.0,8362681,F,200.0,False,...,False,124.5,1988-01-01,NaN,NaN,NaN,NaN,3,33.333333,False
20,90851028,1982-01-01,True,M,NaN,1.0,8951005,F,170.0,False,...,True,124.5,NaN,NaN,NaN,NaN,NaN,14,33.000000,False
21,95763509,1980-01-01,True,F,NaN,1.0,8951005,F,170.0,False,...,True,124.5,NaN,NaN,NaN,NaN,NaN,4,10.500000,False
22,90851028,1982-01-01,True,M,NaN,1.0,8298218,M,190.0,False,...,True,84.8,NaN,NaN,NaN,NaN,NaN,14,39.000000,False
23,93177299,1997-01-01,False,F,1st one-I did not feel like i was taken seriou...,NaN,8983256,F,130.0,False,...,True,84.8,NaN,NaN,NaN,NaN,NaN,6,2.166667,False
24,90851028,1982-01-01,True,M,NaN,1.0,8231652,F,170.0,False,...,False,84.8,1986-01-01,NaN,NaN,NaN,NaN,17,24.647059,False
25,90851028,1982-01-01,True,M,NaN,1.0,8720899,F,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,42.000000,False
26,93556988,1999-01-01,False,F,NaN,1.0,8328549,F,160.0,False,...,True,124.5,NaN,True,NaN,4.8,False,5,12.600000,False
27,95763509,1980-01-01,True,F,NaN,1.0,8328549,F,160.0,False,...,True,124.5,NaN,True,NaN,4.8,False,4,13.500000,False
28,90851028,1982-01-01,True,M,NaN,1.0,8527642,F,170.0,False,...,False,84.8,1989-01-01,NaN,2011-01-01,NaN,NaN,16,25.687500,False
29,95763509,1980-01-01,True,F,NaN,1.0,8527642,F,170.0,False,...,False,84.8,1989-01-01,NaN,2011-01-01,NaN,NaN,4,12.500000,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231559,96114176,1990-01-01,True,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,9,3.444444,False
231560,94703184,NaN,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,2,3.000000,False
231561,92337372,2019-01-01,False,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,1,2.000000,False
231562,95641788,1994-01-01,True,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,8,3.875000,False
231563,97236683,NaN,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,1,4.000000,False
231564,91314347,NaN,False,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,8,3.500000,False
231565,96275085,NaN,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,20,2.750000,False
231566,97864736,1982-01-01,True,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,24,3.333333,False
231567,95714350,1985-01-01,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,30,3.133333,False
231568,95713001,NaN,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,16,3.000000,False
231569,97157437,NaN,True,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,15,6.133333,False
231570,94084925,NaN,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,6,3.833333,True
231571,93353982,NaN,True,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,15,3.200000,False
231572,93671013,1990-01-01,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,36,3.472222,False
231573,90938755,1991-01-01,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,3,3.000000,False
231574,97471870,NaN,True,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,6,2.333333,False
231575,91307952,1994-01-01,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,3,4.000000,False
231576,96872672,NaN,True,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,17,4.294118,True
231577,91970172,NaN,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,2,2.000000,False
231578,98735303,NaN,True,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,4,4.500000,False
231579,99673682,NaN,True,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,7,2.714286,False
231580,92782126,1953-01-01,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,1,4.000000,False
231581,99529401,NaN,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,6,4.000000,False
231582,97929792,1971-01-01,False,M,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,12,2.333333,False
231583,93144839,1993-01-01,False,F,NaN,1.0,8652121,F,180.0,False,...,False,124.5,NaN,NaN,NaN,5.0,True,6,1.166667,False
231584,96636480,1988-01-01,False,F,NaN,1.0,8101426,F,245.0,False,...,False,124.5,1981-01-01,NaN,NaN,NaN,NaN,2,34.000000,False
231585,93923859,NaN,False,M,NaN,1.0,8716807,M,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,18.000000,False
231586,97679954,1984-01-01,True,F,NaN,1.0,8487211,F,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20.000000,False
231587,92951538,NaN,False,F,NaN,1.0,8487211,F,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,45.000000,False
231588,95657962,NaN,False,F,NaN,1.0,8487211,F,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,20.000000,False

In [60]:
# map unique values to number 0 to len of number
len(data.why_looking.unique())

5362

In [53]:
data.ndis

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5          True
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11        False
12          NaN
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          NaN
20          NaN
21          NaN
22          NaN
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
          ...
231559      NaN
231560      NaN
231561      NaN
231562      NaN
231563      NaN
231564      NaN
231565      NaN
231566      NaN
231567      NaN
231568      NaN
231569      NaN
231570      NaN
231571      NaN
231572      NaN
231573      NaN
231574      NaN
231575      NaN
231576      NaN
231577      NaN
231578      NaN
231579      NaN
231580      NaN
231581      NaN
231582      NaN
231583      NaN
231584      NaN
231585      NaN
231586      NaN
231587      NaN
231588      NaN
Name: ndis, Length: 231589, dtype: object